# Jekyll configuration

name: Robbie Cao
description: Software Developer

url: http://robbie-cao.github.io

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl:

social:
  github: robbie-cao
  stackoverflow: robbie-cao
  linkedin: robbie-cao-0967861b
  codepen: 
  instagram: 
  lastfm: 
  rss: feed.xml

share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: true
  pinterest:
  email: true


# Google Analytics key, leave blank to ignore
google_analytics_key: 
# Yandex metrika (https://metrica.yandex.com/) leave blanc to ignore or put true to use
yandex_metrika: 

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: robbie-cao
comments: true

permalink: /:year/:month/:title
gems: [jekyll-paginate]
paginate: 10

#highlighter: rouge
#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)

exclude: ['README.md', 'LICENSE']
